feat add project base config
Undertone0809/gcop pull request #128
Opened 2024-11-24 13:15 UTC by Luffy2004-c

## Description

## Related Issue

## Type of Change

- [ ] 📚 Examples / docs / tutorials / dependencies update
- [ ] 🔧 Bug fix (non-breaking change which fixes an issue)
- [ ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🔐 Security fix

## Checklist

- [ ] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Undertone0809/gcop/blob/main/CODE_OF_CONDUCT.md) document.
- [ ] I've read the [`CONTRIBUTING.md`](https://github.com/Undertone0809/gcop/blob/main/CONTRIBUTING.md) guide.
- [x] I've updated the code style using `make codestyle`.
- [ ] I've written tests for all new methods and classes that I created.
- [ ] I've written the docstring in Google format for all the methods and classes that I used.

2024-11-24 14:32 UTC, Undertone0809 commented
缺文档，可以补充一下使用文档。

2024-11-24 14:34 UTC, Undertone0809 commented
最好创建个单测 mock 一下

2024-11-24 14:36 UTC, Luffy2004-c commented
GET!🙂

2024-11-24 14:38 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +    def get_local_config(self) -> dict:
不要用 dict，用 typing Dict

2024-11-24 14:38 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +    def get_local_config(self) -> dict:
我不知道具体里面有什么字段，可以用 dataclass 声明一下

2024-11-24 15:00 UTC, Luffy2004-c commented on gcop/utils/init_config.py
> +    def get_local_config(self) -> dict:
这个怎么声明，能简单给个example吗？

2024-11-24 15:06 UTC, Luffy2004-c commented on gcop/__main__.py
> +    command = InitConfigCommand()
你是指把init_config的逻辑直接全部搬到这个函数里面来吗？

2024-11-24 15:32 UTC, Undertone0809 commented on gcop/__main__.py
> +    command = InitConfigCommand()
我觉得逻辑可能可以化简一点 但也问题不大 你先写着

2024-11-28 00:16 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +class InitConfigCommand(ConfigFileHandleMixin):
我想说我不太喜欢你这种写法，只有函数单独定义个类有什么意义吗

2024-11-28 00:18 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +class LocalConfig:
叫 ProjectConfig 是不是更合适？

2024-11-28 00:18 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +class LocalConfig:
`~/user/.zeeland/gcop` 下的配置也能叫 LocalConfig

2024-11-28 00:29 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +INIT_CONFIG_COMMAND = "init_project"
你没 get 到我的意思，我是说 `gcop init_project` 这个命令很奇怪，而且在命令行中我们一般用 `gcop init_project`。

不是让你用一个常量， 其他 command 都没用常量就你这个用常量你不觉得很丑吗

2024-11-28 00:32 UTC, Undertone0809 commented
建议把 init_config.py 这个文件删除了

- 首先这个 `init_config.py` 的名字含义不明，local config? project config? 我已经有一个 config,py 文件，这个文件是用来干嘛的？
- 都是 config 为什么不选择都放在 `config.py`  里面呢？

2024-11-28 00:32 UTC, Undertone0809 commented on gcop/utils/init_config.py
> +class InitConfigCommand(ConfigFileHandleMixin):
看看 fastapi，django 的源码看看他们称为 Mixin 的动机是什么，不要乱套设计模式。

2024-11-28 00:37 UTC, Undertone0809 commented
`文档` 也很重要，没有文档等于你没更新这个功能，向大家介绍要如何使用最新发布的功能。

2024-11-28 00:50 UTC, Undertone0809 commented on gcop/__main__.py
> +    if command.handle():
```python
@app.command(name="init-project")
def init_project_command():
    """Initialize gcop config"""
    logger.color_info("Initializing gcop config...")

    cur_path = Path.cwd()
    config_path = cur_path / ".gcop" / "config.yaml"

    if config_path.exists():
        logger.color_info("Gcop config already exists.", color=Color.YELLOW)
        return

    try:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.touch()
    except Exception as e:
        logger.color_info(f"Failed to create gcop config: {e}", color=Color.RED)
        return
```

直接用面向过程写一遍是不是更简单？

2024-11-28 00:56 UTC, Undertone0809 requested changes

2024-11-28 00:56 UTC, Undertone0809 commented on gcop/__main__.py
> +    commit_template = get_local_config().gcoprule or gcop_config.commit_template
为什么这个字段不和 gcop_config 的 commit_template 字段保持一致？这样子会徒增理解成本。

2024-11-28 00:59 UTC, Undertone0809 commented
如果 project 都可以有自己的一套 config，为什么不选择和 gcop_config 使用完全一样的字段和配置呢？你当前的写法只能自定义 commit_template，如果你把 gcop_config 和 project_config 抽象成一套 pattern，是不是可以用相同的方式直接读取项目配置和全局配置呢？

2024-12-08 19:24 UTC, Undertone0809 commented on gcop/config.py
> +def check_model_config(new_model: dict) -> bool:
使用 typing Dict，不要用 dict

2024-12-08 19:28 UTC, Undertone0809 commented on gcop/config.py
> +    project_config_path = Path.cwd() / ".gcop" / "config.yaml"
看起来感觉可以化简

2024-12-20 02:45 UTC, closed without merging